backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: 'event'
    label: 'Event'
    folder: 'content/events'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'event' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - label: 'Event Date'
        name: 'date'
        widget: 'object'
        fields:
          - {
              label: 'Start date',
              name: 'start-date',
              widget: 'datetime',
            }
          - {
              label: 'End date',
              name: 'end-date',
              widget: 'datetime',
            }
      - label: 'Event Location'
        name: 'location'
        widget: 'object'
        fields:
          - { label: 'Name', name: 'location-name', widget: 'string' }
          - { label: 'Street Address', name: 'street', widget: 'string' }
          - { label: 'Postal Code', name: 'post-code', widget: 'string' }
          - { label: 'City', name: 'city', widget: 'string' }
      - { label: 'Facebook Link', name: 'fb-link', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
